from django.conf.urls import url
import django.contrib.auth.views
import genius.views
urlpatterns = [
    url(r'^$', genius.views.home, name='home'),
    url(r'^login$', django.contrib.auth.views.login, {'template_name':'genius/signin.html'}, name='login'),
    url(r'^signup$', genius.views.signup, name='signup'),
    url(r'^email_confirmation$', genius.views.email_confirmation, name='email_confirmation'),
    url(r'^forget_password$', genius.views.forget_password, name='forget_password'),
    url(r'^registration_confirmation/(?P<username>[a-zA-Z0-9_@\+\-]+)/(?P<token>[a-z0-9\-]+)$',
        genius.views.registration_confirmation, name='confirm'),
    url(r'^logout$', django.contrib.auth.views.logout_then_login, name='logout'),
    url(r'^change_password$', genius.views.change_password, name='change_password'),
    url(r'^password_reset_confirmation/(?P<username>[a-zA-Z0-9_@\+\-]+)/(?P<token>[a-z0-9\-]+)$',
        genius.views.password_reset_confirmation, name='password_confirm'),
    url(r'^reset_password/(?P<username>\w+)$', genius.views.reset_password, name='reset_password'),
    url(r'^display_game$', genius.views.display_game, name='display-game'),
    url(r'^math_game$', genius.views.math_game, name='math-game'),
    url(r'^image_matching_game', genius.views.image_matching_game, name='matching-game'),
    url(r'^play_word_snake', genius.views.wordsnake, name ='wordsnake'),
    url(r'^word_snake_start', genius.views.wordsnake_start, name ='wordsnake_start'),
    url(r'^word-snake-end/(?P<score>\w+)$', genius.views.word_snake_end, name='word-snake-end'),
    url(r'^word_snake_review', genius.views.review_words, name='review_wordsnake'),
    url(r'^wordSnake_help', genius.views.wordsnake_help, name='wordsnake_end'),

    url(r'^postendpoint$', genius.views.receiveScore, name = 'word-snake-score'),
    url(r'^play_math_game$', genius.views.play_math_game, name='play-math-game'),
    url(r'^play_image_matching$', genius.views.play_image_matching, name='play-image-matching'),
    url(r'^edit-profile$', genius.views.editProfile,name='edit-profile'),
    # url(r'^upload_image_matching$', genius.views.upload_image_matching, name='upload-image-matching'),
    url(r'^photo/(?P<username>\w+)$', genius.views.get_photo,name='photo'),
    url(r'^get_image_matching_photo/(?P<id>\w+)$', genius.views.get_image_matching_photo,name='matching-game-photo'),
    url(r'^get-question/(?P<game_id>\w+)/(?P<count>\w+)/(?P<choice>.*)$', genius.views.get_question, name='get-question'),
    url(r'^math-game-end/(?P<game_id>\w+)/(?P<count>\w+)/(?P<choice>.*)$', genius.views.math_game_end, name='math-game-end'),
    url(r'^matching-game-end$', genius.views.matching_game_end, name='matching-game-end'),
    url(r'^scoreboard/(?P<game_name>[\w\s+-]+)$', genius.views.scoreboard, name='scoreboard'),
    url(r'^my-page/(?P<game_name>[\w\s+-]+)$', genius.views.my_page, name='my-page'),
    # url(r'^uploads/simple/$', genius.views.simple_upload, name='simple_upload'),
    url(r'^uploads/form/$', genius.views.model_form_upload, name='model_form_upload'),
    # url(r'^picture/(?P<book_id>\w+)$', genius.views.get_cover, name='picture'),
    url(r'^post/(?P<document_id>\d+)$', genius.views.export_auto_doc, name='post'),
    url(r'^sort_by/(?P<category_name>\w+)$', genius.views.sort_by_category, name='sort_category'),
    url(r'^sort_by_level/(?P<level_name>\w+)$', genius.views.sort_by_level, name='sort_level'),
    url(r'^book_info/(?P<book_id>\d+)$', genius.views.get_book_info, name='book_info'),
    url(r'^book_display/(?P<book_id>\d+)$', genius.views.get_book_display, name='book_display'),
    url(r'^reading$', genius.views.reading_home, name='reading_home'),
    url(r'^video$', genius.views.video_home, name='video_home'),
    url(r'^(?P<tag_name>\w+)$', genius.views.video_auto, name ='video-auto'),


    ]
